export const NAV_SCREENS = {
    HOME: "HOME_SCREEN",
    FAVORITES: "FAVORITES_SCREEN",
    NOTIFICATIONS: "NOTIFICATIONS_SCREEN",
    PROFILE: "PROFILE_SCREEN",
    ADD_PRODUCT: "ADD_PRODUCT_SCREEN"
}


